### ISSUE TITLE
给好友发送

### ISSUE THREAD

**Issue by CN-Yi** [Newbe36524/Newbe.Mahua.Framework#103]
// 需要填写以下标记为 TODO 的内容

**基本信息**

Mahua 版本 ： [4.8]
机器人平台 ：[qqlight]

**详细过程**

[TODO填写详细过程]
![image](https://user-images.githubusercontent.com/32233642/76217790-093a2c80-624e-11ea-9286-326946abda89.png)
请求出现服务器内部错误
我本机装有core 2.2和3.1 没有framework 4.7之类的，请问应该怎么解决

错误详情
![image](https://user-images.githubusercontent.com/32233642/76217964-54ecd600-624e-11ea-8cb2-d3d12ad679be.png)

**如何重现**

重现步骤:

1. 接口文档出来后直接调用就就报错

**测试期望**

期望发送出消息，并能接收

**来点截图**

[TODO有图截图]

**系统参数:**

- 操作系统版本: [TODO e.g. Windows 10 home ]
- VS版本： [TODO e.g. VS2019]

**错误日志**

[TODO粘贴一些重要的错误日志]

**额外信息**
![image](https://user-images.githubusercontent.com/32233642/76218499-4c48cf80-624f-11ea-903e-4fc0cad7372b.png)

[TODO添加一些额外信息]

**Comment by newbe36524** [comment]
你调用了 CQP 的API，如果你想要调用 QQLight 的API ，请查看 API文档
