### ISSUE TITLE
支持各平台输出日志api

### ISSUE THREAD

**Issue by bgli100** [Newbe36524/Newbe.Mahua.Framework#34]

**Comment by bgli100** [comment]
对应函数应该是
CQP:  CQ_addLog
Amanda: Api_SendLog
MPQ:  Api_OutPut

**Comment by newbe36524** [comment]
已经输出有文本日志，并且可以使用Nlog具备的众多特性输出到各种地方，不知道是否已经足够满足需求

**Comment by bgli100** [comment]
能够满足，不过建议把log支持的事情写到README或者
http://www.newbe.pro/docs/mahua/2017/12/25/Newbe-Mahua-Tests.html
这里

我重新翻了一下1.6的更新文档才看到这部分内容，这不应该是要了解正常功能所必须的操作

**Comment by newbe36524** [comment]
欢迎 pr
