### ISSUE TITLE
Amanda 异常调用

### ISSUE THREAD

**Issue by shugen002** [Newbe36524/Newbe.Mahua.Framework#35]
目测问题来源

https://github.com/Newbe36524/Newbe.Mahua.Framework/blob/29a3c2f4ddd45ec550aa564bdca0f8f36595f1d4/src/Newbe.Mahua.Amanda/Apis/SendGroupMessageApiMahuaCommandHandler.cs#L17

把群消息几个字删掉就应该没事了

![image](https://user-images.githubusercontent.com/10257291/40325079-0facefea-5d6d-11e8-9fcc-5f4d35b740f3.png)

逐步跟进后，发现上面提到的异常代码，删除后不再报异常调用

**Comment by shugen002** [comment]
貌似不止这一个地方出现了这个中文非代码内容混进里面，还有很多处，希望作者认真检查并尽快发布修改后的包

另外，本人被迫入C#这个鬼坑，别和我说易语言，，，

能否提供一下这个框架的编译指南，谢谢

**Comment by ByboyCn** [comment]
我可以很明确的告诉你 那个是amanda的问题,不是插件的问题

**Comment by newbe36524** [comment]
可联系 Amanda 作者解决此问题
