### ISSUE TITLE
在mpq平台调用GetGroupMemebersWithModel引发异常

### ISSUE THREAD

**Issue by mxyd233** [Newbe36524/Newbe.Mahua.Framework#38]
由GetGroupMemebersWithModelApiMahuaCommand命令引发了异常
EXCEPTION: System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   在 Newbe.Mahua.MPQ.Apis.GetGroupMemebersWithModelApiMahuaCommandHandler.Handle(GetGroupMemebersWithModelApiMahuaCommand message)
   在 MediatR.Internal.RequestHandlerImpl`2.<>c__DisplayClass5_0.<GetHandlerFactory>b__1()
   在 MediatR.Internal.RequestHandlerImpl`2.GetPipeline(TRequest request, RequestHandlerDelegate`1 invokeHandler, MultiInstanceFactory factory)
   在 MediatR.Internal.RequestHandlerImpl`2.Handle(IRequest`1 request, CancellationToken cancellationToken, SingleInstanceFactory singleFactory, MultiInstanceFactory multiFactory)
   在 MediatR.Mediator.Send[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   在 Newbe.Mahua.Commands.CommandCenter.HandleWithResult[TCommand,TResult](TCommand command)
   在 Newbe.Mahua.Commands.ExceptionHandles.ExceptionHandleCommandCenter.Newbe.Mahua.Commands.ICommandCenter.HandleWithResult[TCommand,TResult](TCommand command) 
Stack trace: 
 <>c__DisplayClass5_0.<GetHandlerFactory>b__1 => HandlerExceptionHandler.Handle => LoggedExceptionOccuredMahuaEvent.HandleException

**Comment by newbe36524** [comment]
支持源代码直接调试，欢迎提供解决方案

**Comment by mxyd233** [comment]
在打开mpq后手动再次登录可正常调用，但发现SendGroupMessage(group).Text(“test”)会引发NullReferenceException，SendGroupMessage(group,"text")可正常使用

**Comment by newbe36524** [comment]
更新至 1.9.1 即可修复
