### ISSUE TITLE
ActiveMQ可以集成在本sdk中吗

### ISSUE THREAD

**Issue by DUWENINK** [Newbe36524/Newbe.Mahua.Framework#39]
项目中经常有这样的需求,比如某网站的注册,用户填写了自己的QQ号码之后,网站的QQ机器人可以给用户发送问候信息,用户注册之后触发ActiveMQ的生产者方法,往队列推送自己的QQ号码以及其他信息,然后机器人上边添加一个监听事件,消费者对生产者的数据进行处理,希望楼主可以把这部分内容集成到机器人中

**Comment by DUWENINK** [comment]
`using Newbe.Mahua.MahuaEvents;
using Newbe.Mahua.Plugins.Probe.Services;
using System;
using Apache.NMS;
using Apache.NMS.ActiveMQ;
using Apache.NMS.ActiveMQ.Commands;

namespace Newbe.Mahua.Plugins.Probe.MahuaEvents
{
    /// <summary>
    /// 来自好友的私聊消息接收事件
    /// </summary>
    public class PrivateMessageFromFriendReceivedMahuaEvent
        : IPrivateMessageFromFriendReceivedMahuaEvent
    {
        private readonly IMahuaApi _mahuaApi;
        private readonly IProbe _Probe;
        public PrivateMessageFromFriendReceivedMahuaEvent(
            IMahuaApi mahuaApi, IProbe probe)
        {
            _mahuaApi = mahuaApi;
            _Probe = probe;
        }

        public void ProcessFriendMessage(PrivateMessageFromFriendReceivedContext context)
        {
            // todo 填充处理逻辑
            //throw new NotImplementedException();
            if (context.FromQq == "10223"|| context.FromQq == "15522")
            {
                switch (context.Message)
                {
                    case "开始监控":
                        InitConsumer();
                        _Probe.StartAsync().GetAwaiter().GetResult();
                        break;
                    case "停止监控":
                        _Probe.StopAsnyc().GetAwaiter().GetResult();
                        break;
                }
            }



            // 不要忘记在MahuaModule中注册
        }
        public void InitConsumer()
        {
            //创建连接工厂
            IConnectionFactory factory = new ConnectionFactory("tcp://tencent.duwenink.cn:61616");
            //通过工厂创建连接
            IConnection connection = factory.CreateConnection();
            //连接服务器端的标识
            connection.ClientId = "duwenink";
            //启动连接
            connection.Start();
            //通过连接创建对话
            ISession session = connection.CreateSession();
            //通过会话创建一个消费者
            IMessageConsumer consumer = session.CreateConsumer(new Apache.NMS.ActiveMQ.Commands.ActiveMQQueue("firstQueue"), "filter = 'demo'");
            
            //注册监听事件
            consumer.Listener += consumer_Listener;
            
        }
        void consumer_Listener(IMessage message)
        {

            ITextMessage msg = (ITextMessage)message;

            _mahuaApi.SendGroupMessage("814626997", "测试");
//这里报异常 _mahuaApi 这个生存周期有问题 

        }
    }
}
`
大神帮我看一下这个是为什么啊呜呜呜

**Comment by newbe36524** [comment]
使用MahuaSession  
http://www.newbe.pro/docs/mahua/releasenodes/2018/06/10/Release-Notes-1-9-0.html

**Comment by DUWENINK** [comment]
经过测试可以
