### ISSUE TITLE
统一信息格式

### ISSUE THREAD

**Issue by ArcticLampyrid** [Newbe36524/Newbe.Mahua.Framework#40]
第一次接触，如有打扰还请见谅...
看了下，链式API提供了简易关于发送的统一接口
but，似乎并没有提供关于解析的统一接口（将文本解析成IAt、IText等）

另外，感觉Mahua在某些情况下，把简单的搞复杂了？

**Comment by newbe36524** [comment]
可以在未来的版本中支持文本的正向和反向解析，也欢迎PR
