### ISSUE TITLE
MahuaApi.GetGroupMemberInfo 只要调用就会随机闪退/报错/停止运行的可能性

### ISSUE THREAD

**Issue by LorisYounger** [Newbe36524/Newbe.Mahua.Framework#52]
### 下面分析作废
**详细过程**

正在尝试用用户名代替At，然后发现运行到取用户名值的时候总是闪退，经检查发现 MahuaApi.GetGroupMemberInfo 偶尔会在找不到信息后返回空值，偶尔直接报错程序退出
经过仔细排查，最后发现问题出现在 MahuaApi.GetGroupMemberInfo

**如何重现**

发现问题后，我立即针对 MahuaApi.GetGroupMemberInfo 进行大量测试
经过大量的反复测试，我发现出现闪退的都是使用邮箱为主qq号的qq
其他的就算不在一个群内，都不会出问题 (返回null)

```
//我这里使用的是从CreateSession拿到的api
            IMahuaApi api = MahuaRobotManager.Instance.CreateSession().MahuaApi;
```

例如:   

`api.GetGroupMemberInfo(667244***, 1091196***) //效果:立即闪退`
![image](https://user-images.githubusercontent.com/34806646/47312892-229a0300-d670-11e8-8177-21c6168ad380.png)

`api.GetGroupMemberInfo(667244***, 654284***) //效果:提示错误(软件非try)然后退出
`![image](https://user-images.githubusercontent.com/34806646/47313020-6c82e900-d670-11e8-8533-eb881929e4ef.png)
![image](https://user-images.githubusercontent.com/34806646/47313100-a3f19580-d670-11e8-8882-cfb122e481b8.png)

**测试期望**

不要闪退,不要报错，安安静静的返回null就好了

**来点源代码**

获取用户名字的源代码:
```
IMahuaApi api = MahuaRobotManager.Instance.CreateSession().MahuaApi;

            GroupMemberInfo a = api.GetGroupMemberInfo(groupid, qq);
            if (a != null)
                if (a.InGroupName != "" && !a.InGroupName.Contains("<"))
                    return a.InGroupName;
                else
                    return a.NickName;
            return qq.Remove(qq.Length - 4, 3) + "***";
```

**系统参数:**

- 操作系统版本: win10 1803 (在win7上有同样错误)
- VS版本：vs2017
- CQP 版本 Air 5.11.14A  //PS:会不会这是CQP的原因 我没有使用其他的软件，有待调查

- CPU Intel(R) Core(TM) i7-7700HQ @ 2.80GHz(2808 MHz)
- 内存 Kingston DDR4 2400 8G *2
- 硬盘 SAMSUNG SSD 970PRO (512 GB) INTEL -- SSD 600P (953 GB)

**错误日志**
没找到贴一些不重要的日志

该日志是没闪退成功，只是报错情况下从日志查看器中获取的
很抱歉，酷Q发生错误，无法继续运行。(W0X3E7)
错误模块：未知

[0xE0434352] 发生错误
EAX=0434F810 EBX=00000005 ECX=00000005
EDX=00000000 ESI=0434F8D0 EDI=00000001
EIP=7665DDC2 ESP=0434F810 EBP=0434F868
CS=23 SS=2B DS=2B ES=2B FS=53 GS=2B

[KERNELBASE.dll](0x76550000)->RaiseException(0x10DD60)+0x62=0x7665DDC2
[clr.dll](0x71D50000)+0x155383=0x71EA5383
[clr.dll](0x71D50000)+0x155588=0x71EA5588
[mscorlib.ni.dll](0x6F2A0000)+0x42A91A=0x6F6CA91A
[mscorlib.ni.dll](0x6F2A0000)+0x427E91=0x6F6C7E91
[clr.dll](0x71D50000)+0xEC08=0x71D5EC08
[clr.dll](0x71D50000)+0x16DD11=0x71EBDD11
[clr.dll](0x71D50000)+0x179F93=0x71EC9F93
[clr.dll](0x71D50000)+0xEFF4=0x71D5EFF4
0x0DD19D87
0x0DD1AE0D
0x0DD1AC96
0x035DDADC
[CQP.dll](0x10000000)+0x1C95A3=0x101C95A3
[CQP.dll](0x10000000)+0x1C962D=0x101C962D
[CQP.dll](0x10000000)+0x18F9A=0x10018F9A
[CQP.dll](0x10000000)+0x884A6=0x100884A6
[CQP.dll](0x10000000)+0x85FA7=0x10085FA7
[CQP.dll](0x10000000)+0x8DDE7=0x1008DDE7
[ntdll.dll](0x77690000)->RtlValidSecurityDescriptor(0x62F40)+0x11A=0x776F305A
[ntdll.dll](0x77690000)->RtlValidSecurityDescriptor(0x62F40)+0xEA=0x776F302A

**额外信息**

会不会这是CQP的原因 我没有使用其他的软件，有待调查

联系方式
QQ:707884072

**Comment by LorisYounger** [comment]
![image](https://user-images.githubusercontent.com/34806646/47337509-d6c67880-d6c6-11e8-8a30-346120e25f06.png)
测试了下CLQ也有相同问题

**Comment by wengxt** [comment]
关注一下……我也有同样的问题…似乎并没发现和邮箱之间的联系。

**Comment by LorisYounger** [comment]
对，其实我后面调用用来判断机器人是不是管理员的时候也出现过这个问题
不过还好都是能try回收没啥大碍

**Comment by traceless0929** [comment]
> 对，其实我后面调用用来判断机器人是不是管理员的时候也出现过这个问题
> 不过还好都是能try回收没啥大碍

其实不光判断管理员涉及到群成员的都会崩溃，不给Catch的机会，比如获取群成员列表，并且还不是必现，但是几率不低

**Comment by LorisYounger** [comment]
表示只要调用这个函数，都有概率闪退，而且不能try

**Comment by newbe36524** [comment]
fix by #54
