### ISSUE TITLE
发送私聊消息失败

### ISSUE THREAD

**Issue by DUWENINK** [Newbe36524/Newbe.Mahua.Framework#55]
**详细过程**
问题具体可以归结成这样,之前用的好好的,但是最近更新了vs2017 就异常了,但是不知道问题出在哪
[填写详细过程]
之前写的一个机器人,具体的逻辑是接受到符合条件的消息之后私聊个人,在 **GroupMessageReceivedEvent** 事件里边调用 ```_mahuaApi```的```SendPrivateMessage```方法,但是调用抛异常
**如何重现**

重现步骤:

**测试期望**

[详细描述这个bug的期望]

**来点截图**
![image](https://user-images.githubusercontent.com/16337239/50043106-71c94680-00a9-11e9-9639-7e52daa3f232.png)

[有图截图]

**系统参数:**

- 操作系统版本: [Microsoft Windows [版本 10.0.17134.471] ]
- VS版本： [ VS2017 15.9.4]
-插件版本 1.12.0
**错误日志**
```Newbe.Mahua.Apis.SendPrivateMessageApiMahuaCommand is not registered in this resolver. resolver:StandardResolver```

**额外信息**
这是我的调用信息
<pre><code>
        private readonly IMahuaApi _mahuaApi;
        private GroupConfigEntity _groupConfigEntity;
public GroupMessageReceivedEvent(
            IMahuaApi mahuaApi)
        {
            _mahuaApi = mahuaApi;
            try
            {
                _groupConfigEntity = Tool.GetEntityFromFile<GroupConfigEntity>("GroupConfig.json");

                // 使用浏览器打开定时任务的地址
                //  Process.Start("http://localhost:65238/hangfire/recurring");
            }
            catch
            {
                //ig
            }
        }
</code></pre>

我也在模块里边注册了:

<pre><code>
   private class MahuaEventsModule : Module
        {
            protected override void Load(ContainerBuilder builder)
            {
                base.Load(builder);
                // 将需要监听的事件注册，若缺少此注册，则不会调用相关的实现类
                builder.RegisterType<MyMenuProvider>()
                    .As<IMahuaMenuProvider>();
                builder.RegisterType<MenuClickedEvent>()
                    .As<IMahuaMenuClickedMahuaEvent>();
                builder.RegisterType<GroupMessageReceivedEvent>().As<IGroupMessageReceivedMahuaEvent>();
            }
        }
</code></pre>

**Comment by newbe36524** [comment]
无法知道运行的平台，没有提供文本日志。堆栈不清晰。建议使用简单的代码进行测试后再结合业务代码处理。
