### ISSUE TITLE
[功能请求]忽略框架及依赖的版本

### ISSUE THREAD

**Issue by Cyl18** [Newbe36524/Newbe.Mahua.Framework#59]
多插件的依赖问题会很复杂（Mahua版本不同），而且例如System.ValueTuple的依赖库版本不同也会出很多问题

**Comment by newbe36524** [comment]
需给出相应的实例说明现状与期望

**Comment by Cyl18** [comment]
比如我自己升级了valuetuple 就会出问题

**Comment by newbe36524** [comment]
框架中存在两个 AppDomain ， 由于 主应用程序域的目录在根路径并且没有找到能够建立程序集重定向配置的方法。因此，这个需求可以通过在框架启动时，对程序集加载的错误进行自己处理，进而避免该问题。
提供两种选择：
1. 参考 [解决程序集加载](https://docs.microsoft.com/zh-cn/dotnet/framework/app-domains/resolve-assembly-loads) 相关的方法，可以尝试解决该问题。
2. 在 Newbe.Mahua 2.X 版本后，将采用跨进程通信方案为主，进而将会不存在该问题。并且在 2.X 中，也通过1所属的方案，解决了该问题。[相关代码](https://github.com/newbe36524/Newbe.Mahua.Framework/blob/feature/v2/src/Newbe.Mahua.PluginLoader/PluginInstanceManager.cs#L17)

因此，该问题有两个结论：
1. 开发者可以将2.X版本中的相关代码，恰当的移植到1.X版本中，进而解决问题。
2. 等待2.X版本的发布，使用跨进程通信方案。

欢迎PR

**Comment by newbe36524** [comment]
close this, reopen if you need
