### ISSUE TITLE
自定义回调信息的post地址

### ISSUE THREAD

**Issue by iomect** [Newbe36524/Newbe.Mahua.Framework#61]
目前版本回调是固定post至 http://localhost:65321/api/ReceiveMahuaOutput
如果我的机器人是跑在本地  而回调想提交到服务器就需要二次转发了
正常来说如果是运行在服务器上没啥问题
但我目前的服务器环境均为linux  机器人则只能运行在本地  很难受啊

**Comment by iomect** [comment]
抱歉 打扰了
默默的打开了mahua.json....

**Comment by newbe36524** [comment]
@all-contributors please add @iomect for bug
