### ISSUE TITLE
尝试从一个网络位置加载程序集

### ISSUE THREAD

**Issue by Cyl18** [Newbe36524/Newbe.Mahua.Framework#63]
**详细过程**

![image](https://user-images.githubusercontent.com/14993992/53684827-63580600-3d4d-11e9-9f1d-15b0bbc8addc.png)

**如何重现**

重现步骤:

1. 从网络下载插件, 并使用 Windows 自带解压，即可复现

**测试期望**

Newbe.Mahua 的 App.Config 中启用 loadFromRemoteSources
[http://go.microsoft.com/fwlink/?LinkId=155569](http://go.microsoft.com/fwlink/?LinkId=155569)

**来点截图**

![image](https://user-images.githubusercontent.com/14993992/53684827-63580600-3d4d-11e9-9f1d-15b0bbc8addc.png)

**系统参数:**

- 操作系统版本: [Windows 10 Build 18334]
- VS版本： [VS2019]

**错误日志**

2019-03-03 00:29:27.7174 - ERROR [1]: 未能加载文件或程序集“Newbe.Mahua.PluginLoader, Version=1.15.0.0, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。不支持操作。 (异常来自 HRESULT:0x80131515)
EXCEPTION: System.IO.FileLoadException: 未能加载文件或程序集“Newbe.Mahua.PluginLoader, Version=1.15.0.0, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。不支持操作。 (异常来自 HRESULT:0x80131515)
文件名:“Newbe.Mahua.PluginLoader, Version=1.15.0.0, Culture=neutral, PublicKeyToken=null” ---> System.NotSupportedException: 尝试从一个网络位置加载程序集，在早期版本的 .NET Framework 中，这会导致对该程序集进行沙盒处理。此发行版的 .NET Framework 默认情况下不启用 CAS 策略，因此，此加载可能会很危险。如果此加载不是要对程序集进行沙盒处理，请启用 loadFromRemoteSources 开关。有关详细信息，请参见 http://go.microsoft.com/fwlink/?LinkId=155569。

   在 System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   在 System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   在 System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   在 System.AppDomain.Load(AssemblyName assemblyRef)
   在 System.AppDomain.Load(AssemblyName assemblyRef)
   在 Newbe.Mahua.Domains.DomainLoader.Load()
   在 Newbe.Mahua.PluginInstanceManager.EnsureAppDomainInitialized(PluginFileInfo pluginFileInfo)
   在 Newbe.Mahua.PluginInstanceManager.GetInstance(PluginFileInfo pluginFileInfo)

**额外信息**

喵喵喵

**Comment by newbe36524** [comment]
是否主动尝试开启此程序集远程加载？

是：

如文档所述，在fw4.0之后，需要在关闭CAS之后，再启动该节点配置才能生效。

或者需要修改AppDomain的加载行为，这需要修改DomainLoader的行为，详见堆栈所示相关内容。参看API [UnsafeLoadFrom](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.unsafeloadfrom?redirectedfrom=MSDN&view=netframework-4.7.2#System_Reflection_Assembly_UnsafeLoadFrom_System_String_)


否：

可以做以下尝试：

- 在目标机器上安装fw4.6.2.
- 解锁文件
![default](https://user-images.githubusercontent.com/7685462/53690047-151f2300-3d9e-11e9-8b49-a40e61640007.png)
- 使用管理员身份启动机器人平台
- 关闭UAC

**Comment by newbe36524** [comment]
close this, reopen if you need
