### ISSUE TITLE
i春秋社区机器人

### ISSUE THREAD

**Issue by xxxxbxxxxx** [Newbe36524/Newbe.Mahua.Framework#91]
**这个项目的标题是？**

i春秋社区机器人

**这个项目的公开仓库地址是？**

https://github.com/0nise/ichunqiu_qqbot

**这个项目的简介**

> i春秋社区机器人自`2018年02月04日`开始服务于i春秋社区，每日文章推送、文章查询、魔法币查询、作者信息查询、作家团奖金余额查询、奖金排行榜、i春秋课程查询等一列功能。据不完全统计，使用人数已经超过`3.5万`，使用次数达到`20万`，最大覆盖`700+`个群。

**Comment by newbe36524** [comment]
该项目作为 1.x 的样例已经被添加到 1.x 的版本库中
https://github.com/newbe36524/Newbe.Mahua.Framework.v1
